---

- hosts: all
  become: true
  pre_tasks:

  - name: install apache and PHP packages
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }"
      state: latest
      update_cache: yes

 - name: install updates (CentOS)
   dnf:
     name:
     update_only: yes
     update_cache: yes
   when: asnible_distribution == "CentOS"

 - name: install updates (Ubuntu)
   apt:
     upgrade: dist
     update_cache: yes
   when: asnible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  task:

