---

- hosts: all
  vars_files:
    vars/variables.yml
  pre_tasks:

  - name: install updates (CentOS)
    dnf:
      name:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: webservers
  gather_facts: no
  tasks:

  - name: install apache and PHP packages
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

  - name: start and enable pache service
    tags: apache,httpd
    service:
      name: "{{ apache_service }}"
      state: started
      enable: yes

  - name: Echo invertory_hostname
    ansible.builtin.debug:
      msg:
        - "Hello from ansible playbook!"
        - "This is running on {{ inventory+hostname }}"

  - name: install mariadb package (CentOS)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
