---

- hosts: all
  become: true
  tasks:

  
  - name: update repository index
    yum:
      update_cache: yes  

#   when: ansible_distribution == "CentOS" and ansible_distribution_version == "8.2"  
#   when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install apache2 package
    yum:
      name: apache2
      state: latest

  - name: add php support for apache
    yum: 
      name: libapache2-mod-php
      state: latest

